#!/bin/bash -xe

export PATH=/usr/local/bin:$PATH
export KUBECONFIG=$HOME/.kube/configs/proper-course-kubeconfig.yaml

dir=backups/`date +"%Y-%m-%d-%H-%M"`

mkdir -p $dir

server=$(kubectl get pod -l app=course-server -o jsonpath="{.items[0].metadata.name}")

kubectl cp --retries 3 $server:/storage/course-server.sqlite "$dir/course-server.sqlite"
