#!/bin/bash -xe
version=`scripts/version`
revision=`git rev-parse HEAD`

tags=(--tag llamagraphics/trmnl-tides:$version)
if [[ $version != "dev" ]]
then
    tags+=(--tag llamagraphics/trmnl-tides:latest)
fi

docker buildx build --platform linux/arm64,linux/amd64 \
    --build-arg REVISION=$revision \
    --build-arg VERSION=$version \
    ${tags[@]} --push .
