#!/bin/bash -xe

export PATH=/usr/local/bin:$PATH
export KUBECONFIG=$HOME/.kube/configs/proper-course-kubeconfig.yaml

# This script is adapted from
# https://www.linode.com/docs/guides/how-to-configure-load-balancing-with-tls-encryption-on-a-kubernetes-cluster/#install-the-nginx-ingress-controller

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo add cert-manager https://charts.jetstack.io
helm repo update
helm install ingress-nginx ingress-nginx/ingress-nginx || true

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.crds.yaml
kubectl create namespace cert-manager

helm install \
    my-cert-manager cert-manager/cert-manager \
    --namespace cert-manager \
    --version v1.8.0 || true

kubectl apply -f kubernetes/acme-issuer-prod.yaml
kubectl apply -f kubernetes/course-server-ingress.yaml
