#!/bin/bash -xe

export KUBECONFIG=$HOME/.kube/configs/proper-course-kubeconfig.yaml
context="--context pc"

kubectl $context apply -k kubernetes
kubectl $context scale deploy tides-server --replicas=0
kubectl $context scale deploy tides-server --replicas=1
